---
- name: Add repository rhel-7-server-rpms
  yum_repository:
    name: rhel-7-server-rpms
    description: rhel-7-server-rpms repo
    baseurl: http://172.16.51.66/repos/rhel-7-server-rpms/
    enabled: yes
    gpgcheck: no

- name: Add repository rhel-7-server-extras-rpms
  yum_repository:
    name: rhel-7-server-extras-rpms
    description: rhel-7-server-extras-rpms repo
    baseurl: http://172.16.51.66/repos/rhel-7-server-extras-rpms/
    enabled: yes
    gpgcheck: no

- name: Add repository rhel-7-server-optional-rpms
  yum_repository:
    name: rhel-7-server-optional-rpms
    description: rhel-7-server-optional-rpms repo
    baseurl: http://172.16.51.66/repos/rhel-7-server-optional-rpms/
    enabled: yes
    gpgcheck: no

- name: Add repository rhel-7-server-rh-common-rpms
  yum_repository:
    name: rhel-7-server-rh-common-rpms
    description: rhel-7-server-common-rpms repo
    baseurl: http://172.16.51.66/repos/rhel-7-server-rh-common-rpms/
    enabled: yes
    gpgcheck: no

- name: Add repository rhel-7-server-supplementary-rpms
  yum_repository:
    name: rhel-7-server-supplementary-rpms
    description: rhel-7-server-supplementary-rpms repo
    baseurl: http://172.16.51.66/repos/rhel-7-server-supplementary-rpms/
    enabled: yes
    gpgcheck: no




